server:
  port: 8099
spring:
  datasource:
    driver-class-name: org.h2.Driver
  #driver-class-name: org.mariadb.jdbc.Driver
    #url: jdbc:mariadb://localhost:3306/adg95
    #username: root
    #password: 1234
    url: jdbc:h2:tcp://localhost/~/h2db
    username: sa
    password:
  jpa:
    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
        show_sql: true